server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    url: jdbc:h2:mem:test
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: UTF-8
      schema-locations: classpath:db/schemas.sql
      data-locations: classpath:db/data.sql

logging:
  level:
    root: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
